### ISSUE TITLE
Patches from upstream/master

### ISSUE THREAD

**Issue by nicolaiskogheim** [base-dev/socialite#24]
We are in an alpha-ish state now, and we can take advantage of that by trying out stuff from the master branch in laravel/socialite.

This issue will track those patches.

Patches todo:
- [x] 1723c1a Replaced G+ by OpenID in scopes (in ac1cd0a)
- [x] 79c8984 OpenID isn't necessary (also in ac1cd0a)
- [x] dab36b0 Merge pull request #109 from Max13/patch-1 (aka ac1cd0a)
- [x] 2ef2b9f bitbucket oauth2 #25
- [x] 30cac52 remove use #25
- [x] 7253c66 formating #25
- [x] 659f686 styleCi patch #25
- [x] ~~2979451 Merge pull request #112 from BostjanOb/master~~

List is created by running `git log --oneline --reverse 2.0..master`. The newest commits are at the bottom.
### How create patch

``` sh
# Create a new branch from the `2.0` branch
# I put `master` in the name because we also have patches from upstream/2.0
$ git checkout -b patch-123-master 2.0`

# get the patch
git format-patch -1 <commit-id from list>
0001-Replaced-G-by-OpenID-in-scopes.patch  # <-- example output, a patch file

# apply the patch
git apply 0001-Replaced-G-by-OpenID-in-scopes.patch
```

Some notes regarding patch:
1. `git cherry-pick` can do the same. The error output when a cherry-pick results in a conflict is lacking some information, but it's basically like a rebase in that you get conflicts, fix them, stage them, commit, and then `git cherry-pick --continue`.
2. The patch doesn't always apply. I will update this with some tips, but you can try with the `patch` utility if you have it. For example `patch -p0 < 0001-Replaced-G-by-OpenID-in-scopes.patch`. As patch knows nothing of where your files is supposed to be, you must run this from the project root. `-p0` means that the file paths are relative to the current dir.
3. I haven't tested what `git format-patch` does with a merge commit. Maybe we have to give it a range of the commits in the branch that was merged.
